[aws]
disabled=true

[kubernetes]
disabled=false

[localip]
ssh_only = true
format = "@[$localipv4](bold red) "

[git_metrics]
added_style = "bold red"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
disabled = false
